# Generated by Django 3.0 on 2021-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
